### ISSUE TITLE
Can you provide your code, from the complete STP to the disassembly sequence？Best Wishes!

### ISSUE THREAD

**Issue by Zlzxzw1234** [JoaoPJPrioli/Disassembly-assessment-from-CAD-based-collision-evaluation-for-sequence-planning#1]

**Comment by JoaoPJPrioli** [comment]
Are you interested in developing an commercial app or for academic purposes?

**Comment by Zlzxzw1234** [comment]
I am still a student, mainly used for academic research. Looking forward to your reply










At 2024-01-20 06:21:49, "JoaoPJPrioli" ***@***.***> wrote:

Are you interested in developing an commercial app or for academic purposes?

**Comment by JoaoPJPrioli** [comment]
@Zlzxzw1234 could you share your email so we can talk more?

**Comment by Zlzxzw1234** [comment]
my email is ***@***.***>; and my telephone number is 17810233375 (China); if you have problem, you can call me 










At 2024-01-22 11:20:13, "JoaoPJPrioli" ***@***.***> wrote:

@Zlzxzw1234 could you share your email so we can talk more?

**Comment by JoaoPJPrioli** [comment]
@Zlzxzw1234 git doesn't show your email, could you write your email without the @ char?

**Comment by Zlzxzw1234** [comment]
> @Zlzxzw1234 git doesn't show your email, could you write your email without the @ char?

Zlzxzw1234@163.com
